language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.gradle

script:
    - ./gradlew clean test

after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
